add akka timeout config
Stratio/discovery pull request #244
Opened 2020-11-17 07:38 UTC by drobert-stratio

###### Before submitting the PR, please make sure you do the following 
-  [ ] If there are changes to the backend codebase, run the backend tests with `lein test && lein eastwood && lein bikeshed && lein docstring-checker && ./bin/reflection-linter`
-  [ ] Run the frontend and integration tests with  `yarn lint && yarn flow && yarn test`)
-  [ ] Sign the [Contributor License Agreement](https://docs.google.com/a/metabase.com/forms/d/1oV38o7b9ONFSwuzwmERRMi9SYrhYeOrkbmNaq9pOJ_E/viewform)
(unless it's a tiny documentation change).

2020-11-17 08:34 UTC, darroyocazorla requested changes

2020-11-17 08:34 UTC, darroyocazorla commented on dev.conf
> +include "application"
Usamos únicamente el application.conf mejor

2020-11-17 08:34 UTC, darroyocazorla commented on discovery-cicd-integration/discovery-cicd-service/run
> +java -Dconfig.resource=/dev.conf -jar /app/target/uberjar/discovery-cicd.jar server
Podrías apuntar directamente al application.conf o, simplemente añadir el application.conf al classpath configurando java -cp

2020-11-17 08:34 UTC, darroyocazorla commented on discovery-cicd-integration/discovery-cicd-service/run
> +java -Dconfig.resource=/dev.conf -jar /app/target/uberjar/discovery-cicd.jar server
Añade una variable de entorno DISCOVERY_CICD_JAVA_OPTIONS para poder configurar más cosas en el futuro o, simplemente, si tuviéramos la necesidad de configurar el HEAP

2020-11-17 14:32 UTC, compae commented on discovery-cicd-integration/discovery-cicd-service/application.conf
> +# AKKA HTTP
No habrá que poner las opciones del cliente tambien?

2020-11-17 14:41 UTC, grios-stratio commented on discovery-cicd-integration/discovery-cicd-service/application.conf
> +# AKKA HTTP
Este fichero creo que no lo va a usar el jar de discovery-cicd. habría que meterlo en el repo del discovery-cicd, que ya tenemos allí un application.conf

2020-11-17 14:43 UTC, grios-stratio commented on discovery-cicd-integration/discovery-cicd-service/application.conf
> +akka.http.server.idle-timeout = ${?DISCOVERY_IDLE_TIMEOUT}
El nombre de esta variable de entorno va a dar lugar a confusión, que esto está confiurando una propiedad de discovery-cicd, no de discovery (metabase)

2020-11-17 15:13 UTC, darroyocazorla commented on discovery-cicd-integration/discovery-cicd-service/application.conf
> +akka.http.server.idle-timeout = ${?DISCOVERY_IDLE_TIMEOUT}
+1

2020-11-17 15:16 UTC, darroyocazorla commented on discovery-cicd-integration/discovery-cicd-service/application.conf
> +# AKKA HTTP
Deberíamos tener el reference.conf en el jar en vez del application.conf y que quien quiera pueda tener su application.conf (por ej discovery). Pero ya que está hecho así modifica el application.conf y así no nos complicamos

2020-11-17 15:31 UTC, grios-stratio commented on discovery-cicd-integration/discovery-cicd-service/application.conf
> +# AKKA HTTP
ya pero que ese application.conf no es este, está en el otro repo (pero sí que es verdad que habría que cambiarlo por un reference, pero en el otro repo igualmente, y ya con más calma que un bugfix)

2020-11-27 13:09 UTC, pmarin-stratio requested changes
Falta CHANGELOG

2020-11-27 13:41 UTC, pmarin-stratio approved these changes
LGTM

2020-11-27 14:57 UTC, merged